# BatchScoringDeepLearningModelsWithAML Pipeline 

trigger:
- master

variables:
- group: AzureKeyVault

jobs:
- job: BatchScoringDeepLearningModelsWithAMLJob
  timeoutInMinutes: 300
  cancelTimeoutInMinutes: 2
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - bash: |
      source /usr/share/miniconda/etc/profile.d/conda.sh
      which conda
      conda env create -f environment.yml
      conda activate batchscoringdl_aml
      conda env list  
      echo Login Azure Account
      az login -t $(sptenent) --service-principal -u $(spidentity) --password $(spsecret)
    displayName: 'Initial Step'
  
  - bash: |
      source /usr/share/miniconda/etc/profile.d/conda.sh
      conda activate batchscoringdl_aml
      conda env list  
      echo Execute 01_local_testing.ipynb
      papermill 01_local_testing.ipynb 01_local_testing_output.ipynb --log-output --no-progress-bar -k python3 
    displayName: '01_local_testing.ipynb'
